version: '3.8'

services:
  backend:
    build: ./backend
    container_name: langbud_backend
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    container_name: langbud_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  postgres:
    image: postgres:16
    container_name: langbud_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=languagebuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: