version: '3.8'

services:
  backend:
    build: ./backend
    container_name: langbud_backend
    ports:
      - "8080:8080"

  valkey:
    image: valkey/valkey:latest
    container_name: langbud_valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--appendonly", "yes", "--save", "60", "1", "--loglevel", "warning"]

  mongo:
    image: mongo:latest
    container_name: langbud_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=languagebuddy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  valkey_data:
  mongo_data: