run:
  npm run build && npm run start

test:
  npm run build && npm run test

stream-logs instance:
  ssh wb.maixnor.com 'journalctl -u languagebuddy-api-{{instance}}.service -n 50 -f'

deploy-prod:
  cd .. && nix run .#deploy-prod

deploy-test:
  cd .. && nix run .#deploy-test
