run:
  npm run build && npm run start

test:
  npm run build && npm run test

stream-logs instance:
  ssh wb.maixnor.com 'journalctl -u languagebuddy-api-{{instance}}.service -n 50 -f'

restart instance:
  ssh wb.maixnor.com 'cd ~/repo/languagebuddy && git pull && sudo systemctl restart languagebuddy-api-{{instance}}.service'

