# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@cfworker/json-schema-4.1.1" = {
      name = "_at_cfworker_slash_json-schema";
      packageName = "@cfworker/json-schema";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cfworker/json-schema/-/json-schema-4.1.1.tgz";
        sha512 = "gAmrUZSGtKc3AiBL71iNWxDsyUC5uMaKKGdvzYsBoTW/xi42JQHl7eKV2OYzCUqvc+D2RCcf7EXY2iCyFIk6og==";
      };
    };
    "@ioredis/commands-1.2.0" = {
      name = "_at_ioredis_slash_commands";
      packageName = "@ioredis/commands";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ioredis/commands/-/commands-1.2.0.tgz";
        sha512 = "Sx1pU8EM64o2BrqNpEO1CNLtKQwyhuXuqyfH7oGKCk+1a33d2r5saW8zNwm3j6BTExtjrv2BxTgzzkMwts6vGg==";
      };
    };
    "@langchain/core-0.3.61" = {
      name = "_at_langchain_slash_core";
      packageName = "@langchain/core";
      version = "0.3.61";
      src = fetchurl {
        url = "https://registry.npmjs.org/@langchain/core/-/core-0.3.61.tgz";
        sha512 = "4O7fw5SXNSE+uBnathLQrhm3t+7dZGagt/5kt37A+pXw0AkudxEBvveg73sSnpBd9SIz3/Vc7F4k8rCKXGbEDA==";
      };
    };
    "@langchain/langgraph-0.2.74" = {
      name = "_at_langchain_slash_langgraph";
      packageName = "@langchain/langgraph";
      version = "0.2.74";
      src = fetchurl {
        url = "https://registry.npmjs.org/@langchain/langgraph/-/langgraph-0.2.74.tgz";
        sha512 = "oHpEi5sTZTPaeZX1UnzfM2OAJ21QGQrwReTV6+QnX7h8nDCBzhtipAw1cK616S+X8zpcVOjgOtJuaJhXa4mN8w==";
      };
    };
    "@langchain/langgraph-checkpoint-0.0.18" = {
      name = "_at_langchain_slash_langgraph-checkpoint";
      packageName = "@langchain/langgraph-checkpoint";
      version = "0.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@langchain/langgraph-checkpoint/-/langgraph-checkpoint-0.0.18.tgz";
        sha512 = "IS7zJj36VgY+4pf8ZjsVuUWef7oTwt1y9ylvwu0aLuOn1d0fg05Om9DLm3v2GZ2Df6bhLV1kfWAM0IAl9O5rQQ==";
      };
    };
    "@langchain/langgraph-sdk-0.0.84" = {
      name = "_at_langchain_slash_langgraph-sdk";
      packageName = "@langchain/langgraph-sdk";
      version = "0.0.84";
      src = fetchurl {
        url = "https://registry.npmjs.org/@langchain/langgraph-sdk/-/langgraph-sdk-0.0.84.tgz";
        sha512 = "l0PFQyJ+6m6aclORNPPWlcRwgKcXVXsPaJCbCUYFABR3yf4cOpsjhUNR0cJ7+2cS400oieHjGRdGGyO/hbSjhg==";
      };
    };
    "@langchain/openai-0.5.15" = {
      name = "_at_langchain_slash_openai";
      packageName = "@langchain/openai";
      version = "0.5.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@langchain/openai/-/openai-0.5.15.tgz";
        sha512 = "ANadEHyAj5sufQpz+SOPpKbyoMcTLhnh8/d+afbSPUqWsIMPpEFX3HoSY3nrBPG6l4NQQNG5P5oHb4SdC8+YIg==";
      };
    };
    "@types/json-schema-7.0.15" = {
      name = "_at_types_slash_json-schema";
      packageName = "@types/json-schema";
      version = "7.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-schema/-/json-schema-7.0.15.tgz";
        sha512 = "5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
      };
    };
    "@types/node-18.19.112" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.19.112";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.19.112.tgz";
        sha512 = "i+Vukt9POdS/MBI7YrrkkI5fMfwFtOjphSmt4WXYLfwqsfr6z/HdCx7LqT9M7JktGob8WNgj8nFB4TbGNE4Cog==";
      };
    };
    "@types/node-fetch-2.6.12" = {
      name = "_at_types_slash_node-fetch";
      packageName = "@types/node-fetch";
      version = "2.6.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node-fetch/-/node-fetch-2.6.12.tgz";
        sha512 = "8nneRWKCg3rMtF69nLQJnOYUcbafYeFSjqkw3jCRLsqkWFlHaoQrr5mXmofFGOx3DKn7UfmBMyov8ySvLRVldA==";
      };
    };
    "@types/retry-0.12.0" = {
      name = "_at_types_slash_retry";
      packageName = "@types/retry";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/retry/-/retry-0.12.0.tgz";
        sha512 = "wWKOClTTiizcZhXnPY4wikVAwmdYHp8q6DmC+EJUzAMsycb7HB32Kh9RN4+0gExjmPmZSAQjgURXIGATPegAvA==";
      };
    };
    "@types/uuid-10.0.0" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-10.0.0.tgz";
        sha512 = "7gqG38EyHgyP1S+7+xomFtL+ZNHcKv6DwNaCZmJmo1vgMugyF3TCnXVg4t1uk89mLNwnLtnY3TpOpCOyp1/xHQ==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "accepts-1.3.8" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz";
        sha512 = "PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw+NACSaeXEQ+NHcVF7rONl6qcaxV3Uuemwawk+7+SJLw==";
      };
    };
    "agentkeepalive-4.6.0" = {
      name = "agentkeepalive";
      packageName = "agentkeepalive";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agentkeepalive/-/agentkeepalive-4.6.0.tgz";
        sha512 = "kja8j7PjmncONqaTsB8fQ+wE2mSU2DJ9D4XKoJ5PFWIdRMa6SLSN1ff4mOr4jCbfRSsxR4keIiySJU0N9T5hIQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-5.2.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-5.2.0.tgz";
        sha512 = "Cxwpt2SfTzTtXcfOlzGEee8O+c+MmUgGrNiBcXnuWxuFJHe6a5Hz7qwhwe5OgaSYI0IJvkLqWX1ASG+cJOkEiA==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha512 = "PCVAQswWemu6UdxsDFFX/+gVeYqKAod3D3UVm91jHwynguOwAvYPhx8nNlM++NqRcK6CxxpUafjmhIdKiHibqg==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha512 = "Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q==";
      };
    };
    "atomic-sleep-1.0.0" = {
      name = "atomic-sleep";
      packageName = "atomic-sleep";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
        sha512 = "kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
      };
    };
    "axios-0.27.2" = {
      name = "axios";
      packageName = "axios";
      version = "0.27.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.27.2.tgz";
        sha512 = "t+yRIyySRTp/wua5xEr+z1q60QmLq8ABsS5O9Me1AsE5dfKqgnCFzwiCZZ/cGNd1lq4/7akDWMxdhVlucjmnOQ==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "body-parser-1.20.3" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.20.3.tgz";
        sha512 = "7rAxByjUMqQ3/bHJy7D6OGXvx/MMc4IqBn/X0fcM1QUcAItpZrBEYhWGem+tzXH90c+G01ypMcYJBO9Y30203g==";
      };
    };
    "bufferutil-4.0.9" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.9.tgz";
        sha512 = "WDtdLmJvAuNNPzByAYpRo2rF1Mmradw6gvWsQKf63476DDXmomT9zUiGypLcG4ibIM67vhAj8jJRdbmEws2Aqw==";
      };
    };
    "bytes-3.1.2" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz";
        sha512 = "/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==";
      };
    };
    "call-bind-apply-helpers-1.0.2" = {
      name = "call-bind-apply-helpers";
      packageName = "call-bind-apply-helpers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
        sha512 = "Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
      };
    };
    "call-bound-1.0.4" = {
      name = "call-bound";
      packageName = "call-bound";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
        sha512 = "+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
      };
    };
    "camelcase-6.3.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-6.3.0.tgz";
        sha512 = "Gmy6FhYlCY7uOElZUSbxo2UCDH8owEk996gkbrpsgGtrJLM3J7jGxl9Ic7Qwwj4ivOE5AWZWRMecDdF7hqGjFA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "cluster-key-slot-1.1.2" = {
      name = "cluster-key-slot";
      packageName = "cluster-key-slot";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cluster-key-slot/-/cluster-key-slot-1.1.2.tgz";
        sha512 = "RMr0FhtfXemyinomL4hrWcYJxmX6deFdCxpJzhDttxgO1+bcCnkk+9drydLVDmAMG7NE6aN/fl4F7ucU/90gAA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colorette-2.0.20" = {
      name = "colorette";
      packageName = "colorette";
      version = "2.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-2.0.20.tgz";
        sha512 = "IfEDxwoWIjkeXL1eXcDiow4UbKjhLdq6/EuSVR9GMN7KVH3r9gQ83e73hsz1Nd1T3ijd5xv1wcWRYO+D6kCI2w==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "console-table-printer-2.14.3" = {
      name = "console-table-printer";
      packageName = "console-table-printer";
      version = "2.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-table-printer/-/console-table-printer-2.14.3.tgz";
        sha512 = "X5OCFnjYlXzRuC8ac5hPA2QflRjJvNKJocMhlnqK/Ap7q3DHXr0NJ0TGzwmEKOiOdJrjsSwEd0m+a32JAYPrKQ==";
      };
    };
    "content-disposition-0.5.4" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.4.tgz";
        sha512 = "FveZTNuGw04cxlAiWbzi6zTAL/lhehaWbTtgluJh4/E95DqMwTmha3KZN1aAWA8cFIhHzMZUvLevkw5Rqk+tSQ==";
      };
    };
    "content-type-1.0.5" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz";
        sha512 = "nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==";
      };
    };
    "cookie-0.7.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.7.1.tgz";
        sha512 = "6DnInpx7SJ2AK3+CTUE/ZM0vWTUboZCegxhC2xiIydHR9jNuTAASBrfEpHhiGOZw/nX51bHt6YQl8jsGo4y/0w==";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha512 = "QADzlaHc8icV8I7vbaJXJwod9HWYp8uCqf1xa4OfNu1T7JVxQIrUgOWtHdNDtPiywmFbiS12VjotIXLrKM3orQ==";
      };
    };
    "dateformat-4.6.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "4.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-4.6.3.tgz";
        sha512 = "2P0p0pFGzHS5EMnhdxQi7aJN+iMheud0UhG4dlE1DLAlvL8JHjJJTX/CSm4JXwV0Ka5nGk3zC5mcb5bUQUxxMA==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.4.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.1.tgz";
        sha512 = "KcKCqiftBJcZr++7ykoDIEwSa3XWowTfNPo92BYxjXiyYEVrUQh2aLyhxBCwww+heortUFxEJYcRzosstTEBYQ==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha512 = "z2S+W9X73hAUUki+N+9Za2lBlun89zigOyGrsax+KUQ6wKW4ZoWpEYBkGhQjwAjjDCkWxhY0VKEhk8wzY7F5cA==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha512 = "ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==";
      };
    };
    "denque-2.1.0" = {
      name = "denque";
      packageName = "denque";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-2.1.0.tgz";
        sha512 = "HVQE3AAb/pxF8fQAoiqpvg9i3evqug3hoiwakOyZAwJm+6vZehbkYXZ0l4JxS+I3QxM97v5aaRNhj8v5oBhekw==";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "destroy-1.2.0" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.2.0.tgz";
        sha512 = "2sJGJTaXIIaR1w4iJSNoN0hnMY7Gpc/n8D4qSCJw8QqFWXf7cuAgnEHxBpweaVcPevC2l3KpjYCx3NypQQgaJg==";
      };
    };
    "dotenv-16.5.0" = {
      name = "dotenv";
      packageName = "dotenv";
      version = "16.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotenv/-/dotenv-16.5.0.tgz";
        sha512 = "m/C+AwOAr9/W1UOIZUo232ejMNnJAJtYQjUbHoNTBNTJSvqzzDh7vnrei3o3r3m9blf6ZoDkvcw0VmozNRFJxg==";
      };
    };
    "dunder-proto-1.0.1" = {
      name = "dunder-proto";
      packageName = "dunder-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
        sha512 = "KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha512 = "WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha512 = "TPJXq8JqFaVYm2CWmPvnP2Iyo4ZSM7/QKcSmuMLDObfpH5fi7RUGmd/rTDf+rut/saiDiQEeVTNgAmJEdAOx0w==";
      };
    };
    "encodeurl-2.0.0" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-2.0.0.tgz";
        sha512 = "Q0n9HRi4m6JuGIV1eFlmvJB7ZEVxu93IrMyiMsGC0lrMJMWzRgx6WGquyfQgZVb31vhGgXnfmPNNXmxnOkRBrg==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "end-of-stream-1.4.5" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.5.tgz";
        sha512 = "ooEGc6HP26xXq/N+GCGOT0JKCLDGrq2bQUZrQ7gyrJiZANJ/8YDTxTpQBXGMn+WbIQXNVpyWymm7KYVICQnyOg==";
      };
    };
    "es-define-property-1.0.1" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
        sha512 = "e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.1.1" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
        sha512 = "FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
      };
    };
    "es-set-tostringtag-2.1.0" = {
      name = "es-set-tostringtag";
      packageName = "es-set-tostringtag";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-set-tostringtag/-/es-set-tostringtag-2.1.0.tgz";
        sha512 = "j6vWzfrGVfyXxge+O0x5sh6cvxAog0a/4Rdd2K36zCMV5eJ+/+tOAngRO8cODMNWbVRdVlmGZQL2YS3yR8bIUA==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha512 = "NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha512 = "aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "eventemitter3-4.0.7" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.7.tgz";
        sha512 = "8guHBZCwKnFhYdHr2ysuRWErTwhoN2X8XELRlrRwpmfeY2jjuUN4taQMsULKUVo1K4DvZl+0pgfyoysHxvmvEw==";
      };
    };
    "express-4.21.2" = {
      name = "express";
      packageName = "express";
      version = "4.21.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.21.2.tgz";
        sha512 = "28HqgMZAmih1Czt9ny7qr6ek2qddF4FclbMzwhCREB6OFfH+rXAnuNCwo1/wFvrtbgsQDb4kSbX9de9lFbrXnA==";
      };
    };
    "fast-copy-3.0.2" = {
      name = "fast-copy";
      packageName = "fast-copy";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-copy/-/fast-copy-3.0.2.tgz";
        sha512 = "dl0O9Vhju8IrcLndv2eU4ldt1ftXMqqfgN4H1cpmGV7P6jeB9FwpN9a2c8DPGE1Ys88rNUJVYDHq73CGAGOPfQ==";
      };
    };
    "fast-redact-3.5.0" = {
      name = "fast-redact";
      packageName = "fast-redact";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.5.0.tgz";
        sha512 = "dwsoQlS7h9hMeYUq1W++23NDcBLV4KqONnITDV9DjfS3q1SgDGVrBdvvTLUotWtPSD7asWDV9/CmsZPy8Hf70A==";
      };
    };
    "fast-safe-stringify-2.1.1" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.1.1.tgz";
        sha512 = "W+KJc2dmILlPplD/H4K9l9LcAHAfPtP6BY84uVLXQ6Evcz9Lcg33Y2z1IVblT6xdY54PXYVHEv+0Wpq8Io6zkA==";
      };
    };
    "finalhandler-1.3.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.3.1.tgz";
        sha512 = "6BN9trH7bp3qvnrRyzsBz+g3lZxTNZTbVO2EV1CS0WIcDbawYVdYvGflME/9QP0h0pYlCDBCTjYa9nZzMDpyxQ==";
      };
    };
    "follow-redirects-1.15.9" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz";
        sha512 = "gew4GsXizNgdoRyqmyfMHyAmXsZDk6mHkSxZFCzW9gwlbtOW44CDtYavM+y+72qD/Vq2l550kMF52DT8fOLJqQ==";
      };
    };
    "form-data-4.0.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-4.0.3.tgz";
        sha512 = "qsITQPfmvMOSAdeyZ+12I1c+CKSstAFAwu+97zrnWAbIr5u8wfsExUzCesVLC8NgHuRUqNN4Zy6UPWUTRGslcA==";
      };
    };
    "form-data-encoder-1.7.2" = {
      name = "form-data-encoder";
      packageName = "form-data-encoder";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data-encoder/-/form-data-encoder-1.7.2.tgz";
        sha512 = "qfqtYan3rxrnCk1VYaA4H+Ms9xdpPqvLZa6xmMgFvhO32x7/3J/ExcTd6qpxM0vH2GdMI+poehyBZvqfMTto8A==";
      };
    };
    "formdata-node-4.4.1" = {
      name = "formdata-node";
      packageName = "formdata-node";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-node/-/formdata-node-4.4.1.tgz";
        sha512 = "0iirZp3uVDjVGt9p49aTaqjk84TrglENEDuqfdlZQ1roC9CWlPk6Avf8EEnZNcAqPonwkG35x4n3ww/1THYAeQ==";
      };
    };
    "forwarded-0.2.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
        sha512 = "buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha512 = "zJ2mQYM18rEFOudeV4GShTGIQ7RbzA7ozbU9I/XBpm7kqgMywgmylMwXHxZJmkVoYkna9d2pVXVXPdYTP9ej8Q==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "get-intrinsic-1.3.0" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz";
        sha512 = "9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==";
      };
    };
    "get-proto-1.0.1" = {
      name = "get-proto";
      packageName = "get-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
        sha512 = "sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
      };
    };
    "gopd-1.2.0" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
        sha512 = "ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-symbols-1.1.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
        sha512 = "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "help-me-5.0.0" = {
      name = "help-me";
      packageName = "help-me";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/help-me/-/help-me-5.0.0.tgz";
        sha512 = "7xgomUX6ADmcYzFik0HzAxh/73YlKR9bmFzf51CZwR+b6YtzU2m0u49hQCqV6SvlqIqsaxovfwdvbnsw3b/zpg==";
      };
    };
    "http-errors-2.0.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.0.tgz";
        sha512 = "FtwrG/euBzaEjYeRqOgly7G0qviiXoJWnvEH2Z1plBdXgbyjv34pHTSb9zoeHMyDy33+DWy5Wt9Wo+TURtOYSQ==";
      };
    };
    "humanize-ms-1.2.1" = {
      name = "humanize-ms";
      packageName = "humanize-ms";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/humanize-ms/-/humanize-ms-1.2.1.tgz";
        sha512 = "Fl70vYtsAFb/C06PTS9dZBo7ihau+Tu/DNCk/OyHhea07S+aeMWpFFkUaXRa8fI+ScZbEI8dfSxwY7gxZ9SAVQ==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ioredis-5.6.1" = {
      name = "ioredis";
      packageName = "ioredis";
      version = "5.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ioredis/-/ioredis-5.6.1.tgz";
        sha512 = "UxC0Yv1Y4WRJiGQxQkP0hfdL0/5/6YvdfOOClRgJ0qppSarkhneSa6UvkMkms0AkdGimSH3Ikqm+6mkMmX7vGA==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "joycon-3.1.1" = {
      name = "joycon";
      packageName = "joycon";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/joycon/-/joycon-3.1.1.tgz";
        sha512 = "34wB/Y7MW7bzjKRjUKTa46I2Z7eV62Rkhva+KkopW7Qvv/OSWBqvkSY7vusOPrNuZcUG3tApvdVgNB8POj3SPw==";
      };
    };
    "js-tiktoken-1.0.20" = {
      name = "js-tiktoken";
      packageName = "js-tiktoken";
      version = "1.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tiktoken/-/js-tiktoken-1.0.20.tgz";
        sha512 = "Xlaqhhs8VfCd6Sh7a1cFkZHQbYTLCwVJJWiHVxBYzLPxW0XsoxBy1hitmjkdIjD3Aon5BXLHFwU5O8WUx6HH+A==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "langsmith-0.3.33" = {
      name = "langsmith";
      packageName = "langsmith";
      version = "0.3.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/langsmith/-/langsmith-0.3.33.tgz";
        sha512 = "imNIaBL6+ElE5eMzNHYwFxo6W/6rHlqcaUjCYoIeGdCYWlARxE3CTGKul5DJnaUgGP2CTLFeNXyvRx5HWC/4KQ==";
      };
    };
    "lodash.defaults-4.2.0" = {
      name = "lodash.defaults";
      packageName = "lodash.defaults";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz";
        sha512 = "qjxPLHd3r5DnsdGacqOMU6pb/avJzdh9tFX2ymgoZE27BmjXrNy/y4LoaiTeAb+O3gL8AfpJGtqfX/ae2leYYQ==";
      };
    };
    "lodash.isarguments-3.1.0" = {
      name = "lodash.isarguments";
      packageName = "lodash.isarguments";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isarguments/-/lodash.isarguments-3.1.0.tgz";
        sha512 = "chi4NHZlZqZD18a0imDHnZPrDeBbTtVN7GXMwuGdRH9qotxAjYs3aVLKc7zNOG9eddR5Ksd8rvFEBc9SsggPpg==";
      };
    };
    "math-intrinsics-1.1.0" = {
      name = "math-intrinsics";
      packageName = "math-intrinsics";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
        sha512 = "/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha512 = "dq+qelQ9akHpcOl/gUVRTxVIOkAJ1wR3QAvb4RsVjS8oVoFjDGTc679wJYmUmknUF5HwMLOgb5O+a3KxfWapPQ==";
      };
    };
    "merge-descriptors-1.0.3" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.3.tgz";
        sha512 = "gaNvAS7TZ897/rVaZ0nMtAyxNyi/pdbjbAwUpFQpN70GqnVfOiXpeUUMKRBmzXaSQ8DdTX4/0ms62r2K+hE6mQ==";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha512 = "iclAHeNqNm68zFtnZ0e+1L2yUIdvzNoauKU4WBA3VvH/vPFieF7qfRlwUZU+DA9P9bPXIS90ulxoUoCH23sV2w==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "mustache-4.2.0" = {
      name = "mustache";
      packageName = "mustache";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mustache/-/mustache-4.2.0.tgz";
        sha512 = "71ippSywq5Yb7/tVYyGbkBggbU8H3u5Rz56fH60jGFgr8uHwxs+aSKeqmluIVzM0m0kB7xQjKS6qPfd0b2ZoqQ==";
      };
    };
    "negotiator-0.6.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.3.tgz";
        sha512 = "+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
      };
    };
    "node-cron-4.1.1" = {
      name = "node-cron";
      packageName = "node-cron";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-cron/-/node-cron-4.1.1.tgz";
        sha512 = "oJj9CYV7teeCVs+y2Efi5IQ4FGmAYbsXQOehc1AGLlwteec8pC7DjBCUzSyRQ0LYa+CRCgmD+vtlWQcnPpXowA==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-2.7.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz";
        sha512 = "c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==";
      };
    };
    "node-gyp-build-4.8.4" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.4.tgz";
        sha512 = "LA4ZjwlnUblHVgq0oBF3Jl/6h/Nvs5fzBLwdEF4nuxnFdsfajde4WfxtJr3CaiH+F6ewcIB/q4jQ4UzPyid+CQ==";
      };
    };
    "object-inspect-1.13.4" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.13.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.4.tgz";
        sha512 = "W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wvhAbi4WqjGg9czysTV2Epbew==";
      };
    };
    "on-exit-leak-free-2.1.2" = {
      name = "on-exit-leak-free";
      packageName = "on-exit-leak-free";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-exit-leak-free/-/on-exit-leak-free-2.1.2.tgz";
        sha512 = "0eJJY6hXLGf1udHwfNftBqH+g73EU4B504nZeKpz1sYRKafAghwxEJunB2O7rDZkL4PGfsMVnTXZ2EjibbqcsA==";
      };
    };
    "on-finished-2.4.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz";
        sha512 = "oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "openai-4.104.0" = {
      name = "openai";
      packageName = "openai";
      version = "4.104.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/openai/-/openai-4.104.0.tgz";
        sha512 = "p99EFNsA/yX6UhVO93f5kJsDRLAg+CTA2RBqdHK4RtK8u5IJw32Hyb2dTGKbnnFmnuoBv5r7Z2CURI9sGZpSuA==";
      };
    };
    "openai-5.6.0" = {
      name = "openai";
      packageName = "openai";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/openai/-/openai-5.6.0.tgz";
        sha512 = "jNH5z+hYAdOMZXyEt0yZ7246s+UZjg2AwFQqkAhZIPPjxNtHHO5mykOefau6FkOqj16aC94MOdJl/rZBcKj/cQ==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha512 = "LICb2p9CB7FS+0eR1oqWnHhp0FljGLZCWBE9aix0Uye9W8LTQPwMTYVGWQWIw9RdQiDg4+epXQODwIYJtSJaow==";
      };
    };
    "p-queue-6.6.2" = {
      name = "p-queue";
      packageName = "p-queue";
      version = "6.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-queue/-/p-queue-6.6.2.tgz";
        sha512 = "RwFpb72c/BhQLEXIZ5K2e+AhgNVmIejGlTgiB9MzZ0e93GRvqZ7uSi0dvRF7/XIXDeNkra2fNHBxTyPDGySpjQ==";
      };
    };
    "p-retry-4.6.2" = {
      name = "p-retry";
      packageName = "p-retry";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-retry/-/p-retry-4.6.2.tgz";
        sha512 = "312Id396EbJdvRONlngUx0NydfrIQ5lsYu0znKVUzVvArzEIt08V1qhtyESbGVd1FGX7UKtiFp5uwKZdM8wIuQ==";
      };
    };
    "p-timeout-3.2.0" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-3.2.0.tgz";
        sha512 = "rhIwUycgwwKcP9yTOOFK/AKsAopjjCakVqLHePO3CC6Mir1Z99xT+R63jZxAT5lFZLa2inS5h+ZS2GvR99/FBg==";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "path-to-regexp-0.1.12" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.12.tgz";
        sha512 = "RA1GjUVMnvYFxuqovrEqZoxxW5NUZqbwKtYz/Tt7nXerk0LbLblQmrsgdeOxV5SFHf0UDggjS/bSeOZwt1pmEQ==";
      };
    };
    "pino-9.7.0" = {
      name = "pino";
      packageName = "pino";
      version = "9.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino/-/pino-9.7.0.tgz";
        sha512 = "vnMCM6xZTb1WDmLvtG2lE/2p+t9hDEIvTWJsu6FejkE62vB7gDhvzrpFR4Cw2to+9JNQxVnkAKVPA1KPB98vWg==";
      };
    };
    "pino-abstract-transport-2.0.0" = {
      name = "pino-abstract-transport";
      packageName = "pino-abstract-transport";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-abstract-transport/-/pino-abstract-transport-2.0.0.tgz";
        sha512 = "F63x5tizV6WCh4R6RHyi2Ml+M70DNRXt/+HANowMflpgGFMAym/VKm6G7ZOQRjqN7XbGxK1Lg9t6ZrtzOaivMw==";
      };
    };
    "pino-pretty-13.0.0" = {
      name = "pino-pretty";
      packageName = "pino-pretty";
      version = "13.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-pretty/-/pino-pretty-13.0.0.tgz";
        sha512 = "cQBBIVG3YajgoUjo1FdKVRX6t9XPxwB9lcNJVD5GCnNM4Y6T12YYx8c6zEejxQsU0wrg9TwmDulcE9LR7qcJqA==";
      };
    };
    "pino-std-serializers-7.0.0" = {
      name = "pino-std-serializers";
      packageName = "pino-std-serializers";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-7.0.0.tgz";
        sha512 = "e906FRY0+tV27iq4juKzSYPbUj2do2X2JX4EzSca1631EB2QJQUqGbDuERal7LCtOpxl6x3+nvo9NPZcmjkiFA==";
      };
    };
    "process-warning-5.0.0" = {
      name = "process-warning";
      packageName = "process-warning";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-warning/-/process-warning-5.0.0.tgz";
        sha512 = "a39t9ApHNx2L4+HBnQKqxxHNs1r7KF+Intd8Q/g1bUh6q0WIp9voPXJ/x0j+ZL45KF1pJd9+q2jLIRMfvEshkA==";
      };
    };
    "proxy-addr-2.0.7" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
        sha512 = "llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
      };
    };
    "pump-3.0.3" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.3.tgz";
        sha512 = "todwxLMY7/heScKmntwQG8CXVkWUOdYxIvY2s0VWAAMh/nd8SoYiRaKjlr7+iCs984f2P8zvrfWcDDYVb73NfA==";
      };
    };
    "qs-6.13.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.13.0.tgz";
        sha512 = "+38qI9SOr8tfZ4QmJNplMUxqjbe7LKvvZgWdExBOmd+egZTtjLB67Gu0HRX3u/XOq7UU2Nx6nsjvS16Z9uwfpg==";
      };
    };
    "quick-format-unescaped-4.0.4" = {
      name = "quick-format-unescaped";
      packageName = "quick-format-unescaped";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.4.tgz";
        sha512 = "tYC1Q1hgyRuHgloV/YXs2w15unPVh8qfu/qCTfhTYamaw7fyhumKa2yGpdSo87vY32rIclj+4fWYQXUMs9EHvg==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "raw-body-2.5.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.5.2.tgz";
        sha512 = "8zGqypfENjCIqGhgXToC8aB2r7YrBX+AQAfIPs/Mlk+BtPTztOvTS01NRW/3Eh60J+a48lt8qsCzirQ6loCVfA==";
      };
    };
    "react-19.1.0" = {
      name = "react";
      packageName = "react";
      version = "19.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-19.1.0.tgz";
        sha512 = "FS+XFBNvn3GTAWq26joslQgWNoFu08F4kl0J4CgdNKADkdSGXQyTCnKteIAJy96Br6YbpEU1LSzV5dYtjMkMDg==";
      };
    };
    "real-require-0.2.0" = {
      name = "real-require";
      packageName = "real-require";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/real-require/-/real-require-0.2.0.tgz";
        sha512 = "57frrGM/OCTLqLOAh0mhVA9VBMHd+9U7Zb2THMGdBUoZVOtGbJzjxsYGDJ3A9AYYCP4hn6y1TVbaOfzWtm5GFg==";
      };
    };
    "redis-errors-1.2.0" = {
      name = "redis-errors";
      packageName = "redis-errors";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-errors/-/redis-errors-1.2.0.tgz";
        sha512 = "1qny3OExCf0UvUV/5wpYKf2YwPcOqXzkwKKSmKHiE6ZMQs5heeE/c8eXK+PNllPvmjgAbfnsbpkGZWy8cBpn9w==";
      };
    };
    "redis-parser-3.0.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-3.0.0.tgz";
        sha512 = "DJnGAeenTdpMEH6uAJRK/uiyEIH9WVsUmoLwzudwGJUwZPp80PDBWPHXSAGNPwNvIXAbe7MSUB1zQFugFml66A==";
      };
    };
    "retry-0.13.1" = {
      name = "retry";
      packageName = "retry";
      version = "0.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.13.1.tgz";
        sha512 = "XQBQ3I8W1Cge0Seh+6gjj03LbmRFWuoszgK9ooCpwYIrhhoO80pfq4cUkU5DkknwfOfFteRwlZ56PYOGYyFWdg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-stable-stringify-2.5.0" = {
      name = "safe-stable-stringify";
      packageName = "safe-stable-stringify";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-stable-stringify/-/safe-stable-stringify-2.5.0.tgz";
        sha512 = "b3rppTKm9T+PsVCBEOUR46GWI7fdOs00VKZ1+9c1EWDaDMvjQc6tUwuFyIprgGgTcWoVHSKrU8H31ZHA2e0RHA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "secure-json-parse-2.7.0" = {
      name = "secure-json-parse";
      packageName = "secure-json-parse";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/secure-json-parse/-/secure-json-parse-2.7.0.tgz";
        sha512 = "6aU+Rwsezw7VR8/nyvKTx8QpWH9FrcYiXXlqC4z5d5XQBDRqtbfsRjnwGyqbi3gddNtWHuEk9OANUotL26qKUw==";
      };
    };
    "semver-7.7.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.2.tgz";
        sha512 = "RF0Fw+rO5AMf9MAyaRXI4AV0Ulj5lMHqVxxdSgiVbixSCXoEmmX/jk0CuJw4+3SqroYO9VoUh+HcuJivvtJemA==";
      };
    };
    "send-0.19.0" = {
      name = "send";
      packageName = "send";
      version = "0.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.19.0.tgz";
        sha512 = "dW41u5VfLXu8SJh5bwRmyYUbAoSB3c9uQh6L8h/KtsFREPWpbX1lrljJo186Jc4nmci/sGUZ9a0a0J2zgfq2hw==";
      };
    };
    "serve-static-1.16.2" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.16.2.tgz";
        sha512 = "VqpjJZKadQB/PEbEwvFdO43Ax5dFBZ2UECszz8bQ7pi7wt//PWe1P6MN7eCnjsatYtBT6EuiClbjSWP2WrIoTw==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "side-channel-1.1.0" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.1.0.tgz";
        sha512 = "ZX99e6tRweoUXqR+VBrslhda51Nh5MTQwou5tnUDgbtyM0dBgmhEDtWGP/xbKn6hqfPRHujUNwz5fy/wbbhnpw==";
      };
    };
    "side-channel-list-1.0.0" = {
      name = "side-channel-list";
      packageName = "side-channel-list";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel-list/-/side-channel-list-1.0.0.tgz";
        sha512 = "FCLHtRD/gnpCiCHEiJLOwdmFP+wzCmDEkc9y7NsYxeF4u7Btsn1ZuwgwJGxImImHicJArLP4R0yX4c2KCrMrTA==";
      };
    };
    "side-channel-map-1.0.1" = {
      name = "side-channel-map";
      packageName = "side-channel-map";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel-map/-/side-channel-map-1.0.1.tgz";
        sha512 = "VCjCNfgMsby3tTdo02nbjtM/ewra6jPHmpThenkTYh8pG9ucZ/1P8So4u4FGBek/BjpOVsDCMoLA/iuBKIFXRA==";
      };
    };
    "side-channel-weakmap-1.0.2" = {
      name = "side-channel-weakmap";
      packageName = "side-channel-weakmap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel-weakmap/-/side-channel-weakmap-1.0.2.tgz";
        sha512 = "WPS/HvHQTYnHisLo9McqBHOJk2FkHO/tlpvldyrnem4aeQp4hai3gythswg6p01oSoTl58rcpiFAjF2br2Ak2A==";
      };
    };
    "simple-wcswidth-1.1.1" = {
      name = "simple-wcswidth";
      packageName = "simple-wcswidth";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-wcswidth/-/simple-wcswidth-1.1.1.tgz";
        sha512 = "R3q3/eoeNBp24CNTASEUrffXi0j9TwPIEvSStlvSrsFimM17sV5EHcMOc86j3K+UWZyLYvH0hRmYGCpCoaJ4vw==";
      };
    };
    "sonic-boom-4.2.0" = {
      name = "sonic-boom";
      packageName = "sonic-boom";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-4.2.0.tgz";
        sha512 = "INb7TM37/mAcsGmc9hyyI6+QR3rR1zVRu36B0NeGXKnOOLiZOfER5SA+N7X7k3yUYRzLWafduTDvJAfDswwEww==";
      };
    };
    "split2-4.2.0" = {
      name = "split2";
      packageName = "split2";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split2/-/split2-4.2.0.tgz";
        sha512 = "UcjcJOWknrNkF6PLX83qcHM6KHgVKNkV62Y8a5uYDVv9ydGQVwAHMKqHdJje1VTWpljG0WYpCDhrCdAOYH4TWg==";
      };
    };
    "standard-as-callback-2.1.0" = {
      name = "standard-as-callback";
      packageName = "standard-as-callback";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/standard-as-callback/-/standard-as-callback-2.1.0.tgz";
        sha512 = "qoRRSyROncaz1z0mvYqIE4lCd9p2R90i6GxW3uZv5ucSu8tU7B5HXUP1gG8pVZsYNVaXjk8ClXHPttLyxAL48A==";
      };
    };
    "statuses-2.0.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-2.0.1.tgz";
        sha512 = "RwNA9Z/7PrK06rYLIzFMlaF+l73iwpzsqRIFgbMLbTcLD6cOao82TaWefPXQvB2fOC4AjuYSEndS7N/mTCbkdQ==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "stripe-18.2.1" = {
      name = "stripe";
      packageName = "stripe";
      version = "18.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stripe/-/stripe-18.2.1.tgz";
        sha512 = "GwB1B7WSwEBzW4dilgyJruUYhbGMscrwuyHsPUmSRKrGHZ5poSh2oU9XKdii5BFVJzXHn35geRvGJ6R8bYcp8w==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "thread-stream-3.1.0" = {
      name = "thread-stream";
      packageName = "thread-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thread-stream/-/thread-stream-3.1.0.tgz";
        sha512 = "OqyPZ9u96VohAyMfJykzmivOrY2wfMSf3C5TtFJVgN+Hm6aj+voFhlK+kZEIv2FBh1X6Xp3DlnCOfEQ3B2J86A==";
      };
    };
    "toidentifier-1.0.1" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
        sha512 = "o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "type-is-1.6.18" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.18.tgz";
        sha512 = "TkRKr9sUTxEH8MdfuCSP7VizJyzRNMjj2J2do2Jr3Kym598JVdEksuzPQCnlFPW4ky9Q+iA+ma9BGm06XQBy8g==";
      };
    };
    "undici-types-5.26.5" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "5.26.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-5.26.5.tgz";
        sha512 = "JlCMO+ehdEIKqlFxk6IfVoAUVmgz7cU7zD/h9XZ0qzeosSHmUJVOzSQvvYSYWXkFXC+IfLKSIffhv0sVZup6pA==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha512 = "pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
      };
    };
    "utf-8-validate-6.0.5" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.5.tgz";
        sha512 = "EYZR+OpIXp9Y1eG1iueg8KRsY8TuT8VNgnanZ0uA3STqhHQTLwbl+WX76/9X5OY12yQubymBpaBSmMPkSTQcKA==";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha512 = "pMZTvIkT1d+TFGvDOqodOclx0QWkkgi6Tdoa8gC8ffGAAqz9pzPTZWAybbsHHoED/ztMtkv/VoYTYyShUn81hA==";
      };
    };
    "uuid-10.0.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-10.0.0.tgz";
        sha512 = "8XkAphELsDnEGrDxUOHB3RGvXz6TeuYSGEZBOjtTtPm2lwhGBjLgOzLHB63IUWfBpNucQjND6d3AOudO+H3RWQ==";
      };
    };
    "uuid-9.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-9.0.1.tgz";
        sha512 = "b+1eJOlsR9K8HJpow9Ok3fiWOWSIcIzXodvv0rQjVoOVNpWMpxf1wZNpt4y9h10odCNrqnYp1OBzRktckBe3sA==";
      };
    };
    "validator-13.15.15" = {
      name = "validator";
      packageName = "validator";
      version = "13.15.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-13.15.15.tgz";
        sha512 = "BgWVbCI72aIQy937xbawcs+hrVaN/CZ2UwutgaJ36hGqRrLNM+f5LUT/YPRbo8IV/ASeFzXszezV+y2+rq3l8A==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha512 = "BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
      };
    };
    "web-streams-polyfill-4.0.0-beta.3" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "4.0.0-beta.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-4.0.0-beta.3.tgz";
        sha512 = "QW95TCTaHmsYfHDybGMwO5IJIM93I/6vTRk+daHTWFPhwh+C8Cg7j7XyKrwrj8Ib6vYXe0ocYNrmzY4xAAN6ug==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatsapp-cloud-api-express-3.1.0" = {
      name = "whatsapp-cloud-api-express";
      packageName = "whatsapp-cloud-api-express";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatsapp-cloud-api-express/-/whatsapp-cloud-api-express-3.1.0.tgz";
        sha512 = "uZvSxSnxwD7rXfKq5l93dCrsSnOvPN32V1kHTBcWDoAIDecvNpoPPFsMdE40erserhYsdj9yoA45LXFFuA/QpQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "ws-8.18.2" = {
      name = "ws";
      packageName = "ws";
      version = "8.18.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.18.2.tgz";
        sha512 = "DMricUmwGZUVr++AEAe2uiVM7UoO9MAVZMDu05UQOaUII0lp+zOzLLU4Xqh/JvTqklB1T4uELaaPBKyjE1r4fQ==";
      };
    };
    "zod-3.25.67" = {
      name = "zod";
      packageName = "zod";
      version = "3.25.67";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.67.tgz";
        sha512 = "idA2YXwpCdqUSKRCACDE6ItZD9TZzy3OZMtpfLoh6oPR47lipysRrJfjzMqFxQ3uJuUPyUeWe1r9vLH33xO/Qw==";
      };
    };
    "zod-to-json-schema-3.24.5" = {
      name = "zod-to-json-schema";
      packageName = "zod-to-json-schema";
      version = "3.24.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod-to-json-schema/-/zod-to-json-schema-3.24.5.tgz";
        sha512 = "/AuWwMP+YqiPbsJx5D6TfgRTc4kTLjsh5SOcd4bLsfUg2RcEXrFMJl1DGgdHy2aCfsIA/cr/1JM0xcB2GZji8g==";
      };
    };
  };
  args = {
    name = "languagebuddy-backend";
    packageName = "languagebuddy-backend";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."@cfworker/json-schema-4.1.1"
      sources."@ioredis/commands-1.2.0"
      sources."@langchain/core-0.3.61"
      sources."@langchain/langgraph-0.2.74"
      sources."@langchain/langgraph-checkpoint-0.0.18"
      (sources."@langchain/langgraph-sdk-0.0.84" // {
        dependencies = [
          sources."uuid-9.0.1"
        ];
      })
      (sources."@langchain/openai-0.5.15" // {
        dependencies = [
          sources."openai-5.6.0"
        ];
      })
      sources."@types/json-schema-7.0.15"
      sources."@types/node-18.19.112"
      sources."@types/node-fetch-2.6.12"
      sources."@types/retry-0.12.0"
      sources."@types/uuid-10.0.0"
      sources."abort-controller-3.0.0"
      sources."accepts-1.3.8"
      sources."agentkeepalive-4.6.0"
      sources."ansi-styles-5.2.0"
      sources."argparse-2.0.1"
      sources."array-flatten-1.1.1"
      sources."asynckit-0.4.0"
      sources."atomic-sleep-1.0.0"
      sources."axios-0.27.2"
      sources."base64-js-1.5.1"
      sources."body-parser-1.20.3"
      sources."bufferutil-4.0.9"
      sources."bytes-3.1.2"
      sources."call-bind-apply-helpers-1.0.2"
      sources."call-bound-1.0.4"
      sources."camelcase-6.3.0"
      (sources."chalk-4.1.2" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
        ];
      })
      sources."cluster-key-slot-1.1.2"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colorette-2.0.20"
      sources."combined-stream-1.0.8"
      sources."console-table-printer-2.14.3"
      sources."content-disposition-0.5.4"
      sources."content-type-1.0.5"
      sources."cookie-0.7.1"
      sources."cookie-signature-1.0.6"
      sources."dateformat-4.6.3"
      (sources."debug-2.6.9" // {
        dependencies = [
          sources."ms-2.0.0"
        ];
      })
      sources."decamelize-1.2.0"
      sources."delayed-stream-1.0.0"
      sources."denque-2.1.0"
      sources."depd-2.0.0"
      sources."destroy-1.2.0"
      sources."dotenv-16.5.0"
      sources."dunder-proto-1.0.1"
      sources."ee-first-1.1.1"
      sources."encodeurl-2.0.0"
      (sources."encoding-0.1.13" // {
        dependencies = [
          sources."iconv-lite-0.6.3"
        ];
      })
      sources."end-of-stream-1.4.5"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."es-set-tostringtag-2.1.0"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."event-target-shim-5.0.1"
      sources."eventemitter3-4.0.7"
      sources."express-4.21.2"
      sources."fast-copy-3.0.2"
      sources."fast-redact-3.5.0"
      sources."fast-safe-stringify-2.1.1"
      sources."finalhandler-1.3.1"
      sources."follow-redirects-1.15.9"
      sources."form-data-4.0.3"
      sources."form-data-encoder-1.7.2"
      sources."formdata-node-4.4.1"
      sources."forwarded-0.2.0"
      sources."fresh-0.5.2"
      sources."function-bind-1.1.2"
      sources."get-intrinsic-1.3.0"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-flag-4.0.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."help-me-5.0.0"
      sources."http-errors-2.0.0"
      sources."humanize-ms-1.2.1"
      sources."iconv-lite-0.4.24"
      sources."inherits-2.0.4"
      (sources."ioredis-5.6.1" // {
        dependencies = [
          sources."debug-4.4.1"
        ];
      })
      sources."ipaddr.js-1.9.1"
      sources."joycon-3.1.1"
      sources."js-tiktoken-1.0.20"
      sources."js-yaml-4.1.0"
      sources."langsmith-0.3.33"
      sources."lodash.defaults-4.2.0"
      sources."lodash.isarguments-3.1.0"
      sources."math-intrinsics-1.1.0"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.3"
      sources."methods-1.1.2"
      sources."mime-1.6.0"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimist-1.2.8"
      sources."ms-2.1.3"
      sources."mustache-4.2.0"
      sources."negotiator-0.6.3"
      sources."node-cron-4.1.1"
      sources."node-domexception-1.0.0"
      sources."node-fetch-2.7.0"
      sources."node-gyp-build-4.8.4"
      sources."object-inspect-1.13.4"
      sources."on-exit-leak-free-2.1.2"
      sources."on-finished-2.4.1"
      sources."once-1.4.0"
      sources."openai-4.104.0"
      sources."p-finally-1.0.0"
      sources."p-queue-6.6.2"
      sources."p-retry-4.6.2"
      sources."p-timeout-3.2.0"
      sources."parseurl-1.3.3"
      sources."path-to-regexp-0.1.12"
      sources."pino-9.7.0"
      sources."pino-abstract-transport-2.0.0"
      sources."pino-pretty-13.0.0"
      sources."pino-std-serializers-7.0.0"
      sources."process-warning-5.0.0"
      sources."proxy-addr-2.0.7"
      sources."pump-3.0.3"
      sources."qs-6.13.0"
      sources."quick-format-unescaped-4.0.4"
      sources."range-parser-1.2.1"
      sources."raw-body-2.5.2"
      sources."react-19.1.0"
      sources."real-require-0.2.0"
      sources."redis-errors-1.2.0"
      sources."redis-parser-3.0.0"
      sources."retry-0.13.1"
      sources."safe-buffer-5.2.1"
      sources."safe-stable-stringify-2.5.0"
      sources."safer-buffer-2.1.2"
      sources."secure-json-parse-2.7.0"
      sources."semver-7.7.2"
      (sources."send-0.19.0" // {
        dependencies = [
          sources."encodeurl-1.0.2"
        ];
      })
      sources."serve-static-1.16.2"
      sources."setprototypeof-1.2.0"
      sources."side-channel-1.1.0"
      sources."side-channel-list-1.0.0"
      sources."side-channel-map-1.0.1"
      sources."side-channel-weakmap-1.0.2"
      sources."simple-wcswidth-1.1.1"
      sources."sonic-boom-4.2.0"
      sources."split2-4.2.0"
      sources."standard-as-callback-2.1.0"
      sources."statuses-2.0.1"
      sources."strip-json-comments-3.1.1"
      sources."stripe-18.2.1"
      sources."supports-color-7.2.0"
      sources."thread-stream-3.1.0"
      sources."toidentifier-1.0.1"
      sources."tr46-0.0.3"
      sources."type-is-1.6.18"
      sources."undici-types-5.26.5"
      sources."unpipe-1.0.0"
      sources."utf-8-validate-6.0.5"
      sources."utils-merge-1.0.1"
      sources."uuid-10.0.0"
      sources."validator-13.15.15"
      sources."vary-1.1.2"
      sources."web-streams-polyfill-4.0.0-beta.3"
      sources."webidl-conversions-3.0.1"
      sources."whatsapp-cloud-api-express-3.1.0"
      sources."whatwg-url-5.0.0"
      sources."wrappy-1.0.2"
      sources."ws-8.18.2"
      sources."zod-3.25.67"
      sources."zod-to-json-schema-3.24.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Language Buddy Backend";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
